### ISSUE TITLE
Questionable rendering on Win Chrome 69

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/rubik#4]
For heavier weights, the accents/dots are colliding quite badly.

![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/7525512/68131052-4bf09e80-ff14-11e9-939d-c4755ca9527b.gif)

**Comment by cjdunn** [comment]
@m4rc1e Hmm, it looks like the outlines are identical for the /i and /j when comparing the live google fonts to the masters. So this seems like a hinting/rendering difference. I'm rebuilding using ttfautohint instead of ttfautohint-vf to see if that is more consistent with the live google fonts. Or if you think unhinted would be better we can do that instead. 

Updated versions are in my PR here:
https://github.com/TypeNetwork/rubik/pull/7
